dist: focal
sudo: false

language: go
go:
  - 1.15.x

env:
  - GOFLAGS=-mod=vendor

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

install:
  - bash scripts/gogetcookie.sh

script:
  - make test
  - make vet
  - make website-test

matrix:
  fast_finish: true
  allow_failures:
    - go: master
